/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package encrypt;

/**
 *
 * @author evrob0095
 */
public class encrypt extends javax.swing.JFrame {

    /**
     * Creates new form encrypt
     */
    public encrypt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        decryptLabel = new javax.swing.JLabel();
        input3 = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        input1 = new javax.swing.JTextField();
        encryptLabel = new javax.swing.JLabel();
        decryptButton = new javax.swing.JButton();
        encryptButton = new javax.swing.JButton();
        input2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        decryptLabel.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        decryptLabel.setText("Enter message to be decrypted");
        jPanel1.add(decryptLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        input3.setText("    Encrypted/Decrypted message will output here");
        input3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input3ActionPerformed(evt);
            }
        });
        jPanel1.add(input3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 260, -1));

        titleLabel.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        titleLabel.setText("Encryption Software");
        jPanel1.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input1ActionPerformed(evt);
            }
        });
        jPanel1.add(input1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 160, -1));

        encryptLabel.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        encryptLabel.setText("Enter message to be encrypted");
        jPanel1.add(encryptLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        decryptButton.setText("Decrypt");
        decryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptButtonActionPerformed(evt);
            }
        });
        jPanel1.add(decryptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        encryptButton.setText("Encrypt");
        encryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptButtonActionPerformed(evt);
            }
        });
        jPanel1.add(encryptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        input2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input2ActionPerformed(evt);
            }
        });
        jPanel1.add(input2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input3ActionPerformed

    private void input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input1ActionPerformed

    private void decryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptButtonActionPerformed
        String encrypt = input2.getText();
        String revInput = "";
        String decrypt = "";
        char tempChar;
        int tempASCII = 0;
        
        if (encrypt.length() > 31) {
            input3.setText("Enter a string less than 32 characters long");
        }
        else {
            for (int i = 0; i < encrypt.length(); i++) {
                tempChar = encrypt.charAt(i);
                tempASCII = (int)tempChar;
                tempASCII = tempASCII - 5;
                if (tempASCII < 97) {
                    tempASCII = tempASCII + 26;
                }
                tempChar = (char)tempASCII;
                revInput = revInput+tempChar;
            }
         for (int i = revInput.length() - 1; i >= 0; i--) {
                decrypt = decrypt + revInput.charAt(i);
            }
            input3.setText(decrypt);
        }
    }//GEN-LAST:event_decryptButtonActionPerformed

    private void encryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptButtonActionPerformed
        String input = input1.getText();
        String revInput = "";
        char tempChar;
        int tempASCII = 0;
        String encryption = "";
        if (input.length() > 31) {
            input3.setText("Enter a string less than 32 characters long");
        }
        else {
            for (int i = input.length() - 1; i >= 0; i--) {
                revInput = revInput + input.charAt(i);
            }
            for (int i = 0; i < revInput.length(); i++) {
                tempChar = revInput.charAt(i);
                tempASCII = (int)tempChar;
                if ((tempASCII >=120) && (tempASCII <=122)) {
                    tempASCII = tempASCII -26;
                }
                tempASCII = tempASCII + 5;
                tempChar = (char)tempASCII;
                encryption = encryption + tempChar;
            }
        }
        
        input3.setText(encryption);
    }//GEN-LAST:event_encryptButtonActionPerformed

    private void input2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(encrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(encrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(encrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(encrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new encrypt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton decryptButton;
    private javax.swing.JLabel decryptLabel;
    private javax.swing.JButton encryptButton;
    private javax.swing.JLabel encryptLabel;
    private javax.swing.JTextField input1;
    private javax.swing.JTextField input2;
    private javax.swing.JTextField input3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
